"""Add multi-account support and campaigns table

Revision ID: 81f22004e647
Revises: e237181487fa
Create Date: 2025-05-22 09:18:52.063903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f22004e647'
down_revision = 'e237181487fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'yandex_tokens', ['token_id'], ['id'])

    with op.batch_alter_table('yandex_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_used', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_status', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yandex_tokens', schema=None) as batch_op:
        batch_op.drop_column('last_status')
        batch_op.drop_column('last_used')
        batch_op.drop_column('is_default')
        batch_op.drop_column('is_active')
        batch_op.drop_column('account_name')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('token_id')

    # ### end Alembic commands ###
